### ISSUE TITLE
Convert script not working

### ISSUE THREAD

**Issue by henryruhs** [instant-high/DDColor-onnx#1]
I could not resolve `from basicsr.archs.ddcolor_arch import DDColor`

So I monkey patched the `venv` with this:
https://github.com/camenduru/DDColor/tree/master/basicsr

and uncomment the basicsr version import.

converting to ONNX only worked using absolute paths.

**Comment by instant-high** [comment]
I think I followed the install instructions of the original repo.

During installation there were some version conflicts, as always, so I installed some dependencies without explicit version.

My conversion script is just a modified 'inference/colorization_pipeline.py' script

I also had to set opset version 12, older ones did not work

**Comment by henryruhs** [comment]
whoever is landing here: you need to monkey patch it
